[profile.release]
lto = true

[package]
name = "calculator-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasm-bindgen = "0.2.99"