set windows-shell := ["C:/tools/cygwin/bin/sh.exe","-c"]
set dotenv-load

echo:
	echo $CARGO_TARGET_DIR

#cargo build -p {{crate}} --example {{example}} --target wasm32-unknown-unknown {{args}}
build-wasm example *args:
	cargo build --example {{example}} --target wasm32-unknown-unknown {{args}}
	wasm-bindgen \
	--out-dir ./html/wasm \
	--out-name bindgen \
	--target web \
	$CARGO_TARGET_DIR/wasm32-unknown-unknown/debug/examples/{{example}}.wasm
# --no-typescript \