set windows-shell := ["C:/tools/cygwin/bin/sh.exe","-c"]
set dotenv-load

echo:
	echo $CARGO_TARGET_DIR

build:
	just watch 'just build-wasm calculator'


#cargo build -p {{crate}} --example {{example}} --target wasm32-unknown-unknown {{args}}
build-wasm example *args:
	cargo build --example {{example}} --target wasm32-unknown-unknown {{args}}
	wasm-bindgen \
	--out-dir ./html/wasm \
	--out-name bindgen \
	--target web \
	$CARGO_TARGET_DIR/wasm32-unknown-unknown/debug/examples/{{example}}.wasm
	just copy-wasm

copy-wasm:
	rm -rf ../calculator-astro/wasm
	cp -rf ./html/wasm ../calculator-astro


watch *command:
	forky watch \
	-w '**/*.rs' \
	-i '{.git,target,html}/**' \
	-i '**/mod.rs' \
	-- {{command}}